### ISSUE TITLE
Dictionary frame not showing up.

### ISSUE THREAD

**Issue by ezxpro** [gustavklopp/LingL#16]
Following the latest release I can finally read the texts, however, the lower frame where the word definition is shown is not displaying. 
![image](https://user-images.githubusercontent.com/15344931/119661551-c9d20e80-be06-11eb-9c98-0b5f273a4103.png)

Same happens on both chrome and firefox, although chrome just displays a sad emoji. If I click the "learn more" button in firefox, it takes me to [this page](https://support.mozilla.org/en-US/kb/xframe-neterror-page?as=u&utm_source=inproduct)

Clicking the "open in new window" button takes me to the following page 404 error page:
![image](https://user-images.githubusercontent.com/15344931/119661913-2b927880-be07-11eb-8cc8-29573f3f800d.png)

**Comment by gustavklopp** [comment]
Thanks for reporting! I've published a new release, it should work now.

**Comment by ezxpro** [comment]
I'm  checking it right now

**Comment by ezxpro** [comment]
I can confirm the issue still remains in version 2021.05.27
![image](https://user-images.githubusercontent.com/15344931/119833595-9d38f800-bed5-11eb-8249-3d82082f421f.png)

**Comment by gustavklopp** [comment]
I couldn't reproduced your error:

![Zaslonska slika 2021-05-28 05-40-23](https://user-images.githubusercontent.com/6438275/119926253-4edc3580-bf77-11eb-8406-1f92b0c76193.png)

Have you deleted the program folder and use the new release?
I have used the backup file that you've uploaded previously: 
[OLDLWT_BACKUP_ezxpro.sql.gz](https://github.com/gustavklopp/LingL/files/6558016/OLDLWT_BACKUP_ezxpro.sql.gz)

In Language detail for German, can you show me what  the links for the 1st and the 2nd dictionary are?
Here's what I've got:

![Zaslonska slika 2021-05-28 05-44-06](https://user-images.githubusercontent.com/6438275/119926450-c01be880-bf77-11eb-9943-8cc5cecb71d1.png)

**Comment by ezxpro** [comment]
Ok, I'm gonna check that ASAP.

**Comment by ezxpro** [comment]
Well, it seems like upon importing the database, the dictionary config turned out to be empty:

![image](https://user-images.githubusercontent.com/15344931/120107202-79c0b800-c136-11eb-9967-40b1d65f3234.png)


I set it like yours
![image](https://user-images.githubusercontent.com/15344931/120107245-aaa0ed00-c136-11eb-9df8-298f92f7637e.png)


And dict.cc worked. Wordreference gives me this:

![image](https://user-images.githubusercontent.com/15344931/120107271-cad0ac00-c136-11eb-90df-6a423cd2ab8b.png)

**Comment by gustavklopp** [comment]
Today release should fix it. Some dictionary links now are like '!https://....': It means you can directly click on the translation to add it.

**Comment by dodanghoanganh** [comment]
Many thanks!

**Comment by ezxpro** [comment]
I just noticed now that this issue with the frame is sometimes happening even if the dictionary links  are set up.
See:

https://user-images.githubusercontent.com/15344931/120240645-7c570680-c237-11eb-8d50-a27086facb40.mp4


However, if I replace dict.cc's URL with `https://www.dict.cc/?s=###` the problem is gone
It might or might not be useful, but I just remembered I had the exact same issue with LWT when trying to use Collins as a dictionary (`https://www.collinsdictionary.com/dictionary/german-english/###`), and I just made a test and the same happens in LingL with collins.

**Comment by gustavklopp** [comment]
> I just noticed now that this issue with the frame is sometimes happening even if the dictionary links are set up.

Yes, it's due to the fact that a lot of dictionary websites [don't like that we display their website by another way than going on their website](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)... 
I've made a section in the Help page about it: go to [http://127.0.0.1:8000/helppage#dicturi](http://127.0.0.1:8000/helppage#dicturi) in LingL to have a more precise explanation.

I'm releasing little by little APIs for dictionary to circumvent it: Only add a '!' in front of the URL. I've already created APIs working for Google translate, dict.cc, wordreference, wiktionary. 
If the API is not ready yet, you can still use a '*' (it will open in a new window) or a '^' (it will scrape the entire webpage).

**Comment by ezxpro** [comment]
> Yes, it's due to the fact that a lot of dictionary websites [don't like that we display their website by another way than going on their website](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)...

> If the API is not ready yet, you can still use a '*' (it will open in a new window) or a '^' (it will scrape the entire webpage).

Cool, thanks for all the info

**Comment by gustavklopp** [comment]
So can I close the issue now?

**Comment by ezxpro** [comment]
Yes,  I think you can

**Comment by gustavklopp** [comment]
Thanks again for reporting!
